# Generated by Django 3.2 on 2021-04-08 19:17

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateField()),
                ('end_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'governments',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('born_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=15, null=True)),
                ('type', models.CharField(choices=[('nazi', 'nazi'), ('liberals', 'liberals'), ('populists', 'populists'), ('communists', 'communists'), ('conservatives', 'conservatives'), ('socialists', 'socialists'), ('nationalists', 'nationalists'), ('democrats', 'democrats')], max_length=100, null=True, verbose_name=apps.core.models.Party.PartyEnum)),
                ('founded_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'parties',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(db_table='role_permissions', to='core.Permission')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='GovernmentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_members', to='core.government')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_members', to='core.member')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_members', to='core.party')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_members', to='core.role')),
            ],
            options={
                'db_table': 'government_members',
            },
        ),
    ]
