# Generated by Django 3.0.4 on 2020-03-28 18:35

import apps.core.models
from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='founded_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('nazi', 'nazi'), ('simple', 'simple'), ('liberal', 'liberal'), ('populist', 'populist'), ('communist', 'communist'), ('conservative', 'conservative')], enum_class=apps.core.models.Party.PartyEnum, max_length=12, null=True),
        ),
    ]
