# Generated by Django 3.0.4 on 2020-03-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_party_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='end_at',
            field=models.DateField(null=True),
        ),
    ]
