# Generated by Django 3.0.4 on 2020-03-29 20:03

import apps.core.models
from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_party_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('nazi', 'nazi'), ('liberals', 'liberals'), ('populists', 'populists'), ('communists', 'communists'), ('conservatives', 'conservatives'), ('socialists', 'socialists'), ('nationalists', 'nationalists'), ('democrats', 'democrats')], enum_class=apps.core.models.Party.PartyEnum, max_length=13, null=True),
        ),
    ]
